In [1]:
import numpy as np

In [2]:
#Convert a Python list x=[[1,2,3],[4,5,6]] into a Numpy array.
x=[[1,2,3],[4,5,6]]
a = np.array(x)
print(a)
print(type(a))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [3]:
#Use one line to create a 3x2 2D array with shape of (3,2), filled with 1-6.
#Note: if you use more than 1 line code to complete it, no point.

rng = np.random.default_rng(seed = 1)
arr = rng.integers(1,6,size = (3,2))
print(arr)
print("note : in the above 6 is excluded, in case 6 is to be included : ")
rng = np.random.default_rng(seed = 1)
arr = rng.integers(1,7,size = (3,2))
print(arr)


[[3 3]
 [4 5]
 [1 1]]
note : in the above 6 is excluded, in case 6 is to be included : 
[[3 4]
 [5 6]
 [1 1]]


In [4]:
#3). Use one line to create an array of 2, 4, 6, 8, ..., 98, 100; and find the mean value.
m = np.arange(2,101,2).mean()
print("mean : ",m)

mean :  51.0


In [5]:
#4). Create an 3x3x3 array filled with arbitrary float numbers; and find the minimum and maximum values.

b =  rng.random(size = (3,3,3))
print(b)

print("min : ",b.min())
print("max : ",b.max())


[[[0.94864945 0.31183145 0.42332645]
  [0.82770259 0.40919914 0.54959369]
  [0.02755911 0.75351311 0.53814331]]

 [[0.32973172 0.7884287  0.30319483]
  [0.45349789 0.1340417  0.40311299]
  [0.20345524 0.26231334 0.75036467]]

 [[0.28040876 0.48519097 0.9807372 ]
  [0.96165719 0.72478994 0.54122686]
  [0.2768912  0.16065201 0.96992541]]]
min :  0.027559113243068367
max :  0.9807371998012386


In [6]:
#5). Create a 3x4 2D array filled with values from 10 to 21 (included).

rng = np.random.default_rng(seed = 22)
arr = rng.integers(10,22,size=(3,4))
print(arr)
 # another variation possible :


arr = rng.uniform(10,22,size=(3,4))
print(arr)


[[19 14 17 12]
 [21 11 13 17]
 [10 15 11 21]]
[[20.21881684 20.04353588 10.61726521 16.66414186]
 [17.28957432 10.60169554 15.72793543 13.95476571]
 [12.59782818 19.56420079 15.05078668 11.2381973 ]]


In [7]:
#6). Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.
arr = np.arange(5,5+(10*3),3)
print(arr)

[ 5  8 11 14 17 20 23 26 29 32]


In [8]:
#7). Create a shape (10,10) array with arbitrary values; and find the memory size of this array.

c = rng.random(size=(10,10))
print(c)
m = c.nbytes
print(f"mermory size : {m} bytes")

[[0.36907062 0.91484443 0.38959715 0.18733586 0.06673616 0.51217156
  0.66755598 0.41280958 0.8483194  0.52448906]
 [0.79743431 0.5651524  0.5907989  0.41249658 0.10972016 0.70459029
  0.85839343 0.72502816 0.41956598 0.08710748]
 [0.18578912 0.55126461 0.6588493  0.02637789 0.94292004 0.71462021
  0.72238854 0.98817391 0.6208241  0.49242975]
 [0.22440346 0.68524315 0.69935244 0.95271664 0.93396932 0.49131383
  0.85253565 0.95803477 0.41673202 0.60638143]
 [0.59347973 0.48045434 0.46904558 0.22156125 0.18759859 0.30837304
  0.59205382 0.65949528 0.81936355 0.28693058]
 [0.51581704 0.45332777 0.17050484 0.98173608 0.33552109 0.690731
  0.69145228 0.77085442 0.83338447 0.94645799]
 [0.32084921 0.6683858  0.31679656 0.29787818 0.792785   0.74951083
  0.73189037 0.12280218 0.9672186  0.62830826]
 [0.46489151 0.91285937 0.11170843 0.30129381 0.14317208 0.32746575
  0.78677869 0.14981876 0.76134091 0.59801706]
 [0.32959879 0.8497573  0.04250395 0.2435405  0.50023569 0.40023482
  0.38475551 0

In [9]:
#8). Create a 1-d array of size 10 with arbitrary values but the fifth value should be 5.
a = rng.random(size=(10))
print("numpy array created : ",a)
a[4]=5
print("")
print("5th element : ",a[4])
print("")
print("after changes made : \n",a)

# OR u can directly use : np.put() :

a = rng.random(size=(10))
print("numpy array created : ",a)

np.put(a,4,5)
#  basically we are replacing the index =4, i.e the 5th posn. with value = 5

numpy array created :  [0.04818348 0.79737981 0.73278585 0.09407911 0.71234825 0.33925691
 0.43221011 0.20151398 0.68798465 0.57787109]

5th element :  5.0

after changes made : 
 [0.04818348 0.79737981 0.73278585 0.09407911 5.         0.33925691
 0.43221011 0.20151398 0.68798465 0.57787109]
numpy array created :  [0.02293303 0.1495296  0.73238908 0.13441133 0.46681793 0.66912565
 0.16968739 0.49785333 0.42019396 0.14039249]


In [10]:
#9). Create an array with values ranging from 10 to 49 (included); and reverse it then (first element becomes last).

arr = rng.integers(10,50,size=(10))
print(f'actual array : {arr}')
arr_rev =  np.flip(arr)
print(f"reversed numpy array : {arr_rev}")


actual array : [45 41 37 13 10 43 39 23 48 24]
reversed numpy array : [24 48 23 39 43 10 13 37 41 45]


In [11]:
#10). Create an array of shape (3, 2) with random values from a uniform distribution over [0, 1) and confirm you can get the same value when you run it next time.

rng = np.random.default_rng(seed = 50)
arr = rng.random(size = (3,2))
print("1st array : ",arr)


nrg = np.random.default_rng(seed = 50)
brr = nrg.random(size = (3,2))
print("2nd array : ",brr)

# This occurs because i am using the same seed value




1st array :  [[0.78742269 0.83366933]
 [0.54790446 0.9734491 ]
 [0.23683356 0.64692334]]
2nd array :  [[0.78742269 0.83366933]
 [0.54790446 0.9734491 ]
 [0.23683356 0.64692334]]


In [12]:
student_data = [[1, 15],[2, 11],[3, 11],[4, 20]]
print(type(student_data))

<class 'list'>


In [13]:
arr = np.array([0.,1.,2.,3.,4.])
print(arr)
matrix = np.tile(arr,(5,1))
print("------------------------------")
print(matrix)

[0. 1. 2. 3. 4.]
------------------------------
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
import numpy as np

# Original array
org_arr = np.ones((5, 5))

# Create a new array with zeros and insert the original array in the center
new_arr = np.zeros((org_arr.shape[0] + 2, org_arr.shape[1] + 2))
new_arr[1:-1, 1:-1] = org_arr

print(new_arr)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [15]:
import numpy as np

# Create a 5x5 array with values 1, 2, 3, 4, 5 on the diagonal
diagonal_array = np.diag([1, 2, 3, 4, 5])

# Move 1, 2, 3, 4 below the diagonal
moved_below_diagonal = np.triu(diagonal_array, k=-1)

# Display the results
print("Original Diagonal Array:")
print(diagonal_array)
print("\nMoved Below Diagonal:")
print(moved_below_diagonal)



Original Diagonal Array:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]

Moved Below Diagonal:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [16]:
import numpy as np

# Create a 10x10 array filled with zeros
array = np.zeros((10, 10))

# Set the border elements to 1
array[0, :] = 1
array[-1, :] = 1
array[:, 0] = 1
array[:, -1] = 1

print(array)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Adjust the size as needed

# Method 1: Using numpy.floor()
integer_part_method_1 = np.floor(random_array).astype(int)

# Method 2: Using astype(int)
integer_part_method_2 = random_array.astype(int)

print("Original Array:")
print(random_array)
print("\nMethod 1 - Integer Part:")
print(integer_part_method_1)
print("\nMethod 2 - Integer Part:")
print(integer_part_method_2)


Original Array:
[8.34137214 1.66025691 7.07208922 1.01199352 5.985493  ]

Method 1 - Integer Part:
[8 1 7 1 5]

Method 2 - Integer Part:
[8 1 7 1 5]


In [18]:
x = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]

# Find the indices of all occurrences of 1
indices_of_1 = [index for index, value in enumerate(x) if value == 1]

# Check if there are at least 5 occurrences of 1
if len(indices_of_1) >= 5:
    # Get the index of the 5th occurrence of 1
    fifth_occurrence_index = indices_of_1[4]
    print("Index of the 5th repetition of 1:", fifth_occurrence_index)
else:
    print("There are less than 5 occurrences of 1 in the array.")

Index of the 5th repetition of 1: 8


In [19]:
import numpy as np

# Create an array using np.arange
original_array = np.arange(1, 10)

# Split original_array into sub-arrays with lengths 4, 2, and 3
sub_arrays = np.split(original_array, [4, 6])

# Display the result
print("Original Array:")
print(original_array)
print("\nSub-arrays:")
for i, sub_array in enumerate(sub_arrays, 1):
    print(f"Sub-array {i}: {sub_array}")


Original Array:
[1 2 3 4 5 6 7 8 9]

Sub-arrays:
Sub-array 1: [1 2 3 4]
Sub-array 2: [5 6]
Sub-array 3: [7 8 9]


In [20]:
import numpy as np

# Generate the 2D array using np.arange
original_array = np.arange(16).reshape((4, 4))

# Split the array into left and right halves
left_half, right_half = np.split(original_array, [2], axis=1)

# Display the result
print("Original Array:")
print(original_array)
print("\nLeft Half:")
print(left_half)
print("\nRight Half:")
print(right_half)



Original Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Left Half:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Right Half:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [21]:
import numpy as np

# Given 2D array
original_array = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

# (1) Slicing to get the sub-array [[10, 15], [25, 30]]
sub_array = original_array[0:2, 1:]

# (2) Getting individual element value "20"
element_value = original_array[1, 0]

# Display the results
print("Original Array:")
print(original_array)

print("\n(1) Sub-array:")
print(sub_array)

print("\n(2) Individual Element Value:")
print(element_value)


Original Array:
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]

(1) Sub-array:
[[10 15]
 [25 30]]

(2) Individual Element Value:
20


In [22]:
import numpy as np

# Given arrays x and y
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate x and y along the second axis
result_array = np.concatenate((x, y), axis=1)

# Alternative: result_array = np.hstack((x, y))

# Display the result
print("Concatenated Array:")
print(result_array)


Concatenated Array:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [23]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate a random 2D array with shape (5, 3) and values in the range [1, 10)
random_array = np.random.randint(1, 10, size=(5, 3))

# Compute the min/max ratio for each row
min_max_ratio = np.min(random_array, axis=1) / np.max(random_array, axis=1)

# Display the results
print("Random 2D Array:")
print(random_array)
print("\nMin/Max Ratio for Each Row:")
print(min_max_ratio)


Random 2D Array:
[[7 4 8]
 [5 7 3]
 [7 8 5]
 [4 8 8]
 [3 6 5]]

Min/Max Ratio for Each Row:
[0.5        0.42857143 0.625      0.5        0.5       ]


In [24]:
import numpy as np

# Generate a random 5x5 matrix
random_matrix = np.random.rand(5, 5)

# Calculate mean and standard deviation
mean_value = np.mean(random_matrix)
std_deviation = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean_value) / std_deviation

# Display the results
print("Random 5x5 Matrix:")
print(random_matrix)
print("\nNormalized 5x5 Matrix:")
print(normalized_matrix)


Random 5x5 Matrix:
[[0.96990985 0.83244264 0.21233911 0.18182497 0.18340451]
 [0.30424224 0.52475643 0.43194502 0.29122914 0.61185289]
 [0.13949386 0.29214465 0.36636184 0.45606998 0.78517596]
 [0.19967378 0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]

Normalized 5x5 Matrix:
[[ 1.76878353  1.29186016 -0.85950282 -0.9653674  -0.95988739]
 [-0.54065768  0.22438564 -0.09761066 -0.58580483  0.52655471]
 [-1.11222928 -0.5826286  -0.32514236 -0.01391244  1.12787499]
 [-0.90344341  0.18788105  0.45911614 -1.43503059  0.51160855]
 [-1.0045741  -1.37049638  1.6958426   1.75394224  1.20843836]]


In [25]:
import numpy as np

# Generate the three arrays using numpy arange()
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)

# Concatenate the arrays into a single 1D array
result_array = np.concatenate((arr1, arr2, arr3))

# Display the result
print(result_array)


[0 1 2 3 4 5 6 7 8 9]


In [26]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate a 1D array of uniformly distributed integers
aa = np.random.randint(0, 100, size=20)

# Extract items between 15 and 55 using a boolean mask
result_items = aa[(aa >= 15) & (aa <= 55)]

# Display the results
print("Original Array (aa):")
print(aa)
print("\nItems between 15 and 55:")
print(result_items)


Original Array (aa):
[51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]

Items between 15 and 55:
[51 20 23 21 52 29 37]


In [27]:
import numpy as np

a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

# Get the positions where elements of a and b match
matching_positions = np.where(a == b)

# Display the result
print("Matching Positions:")
print(matching_positions)


Matching Positions:
(array([1, 3, 5, 7], dtype=int64),)


In [28]:
import numpy as np

# Create an array from 0 to 19
original_array = np.arange(20)

# Replace all odd numbers with -1
modified_array = np.where(original_array % 2 != 0, -1, original_array)

# Display the results
print("Original Array:")
print(original_array)
print("\nModified Array:")
print(modified_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Modified Array:
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [29]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a four-dimensional array with random values (0-9)
four_dim_array = np.random.randint(0, 10, size=(3, 4, 3, 4))

# Get the sum over the last two axes (axis=(2, 3))
sum_over_last_two_axes = np.sum(four_dim_array, axis=(2, 3))

# Display the results
print("Original Four-Dimensional Array:")
print(four_dim_array)
print("\nSum Over the Last Two Axes:")
print(sum_over_last_two_axes)


Original Four-Dimensional Array:
[[[[6 3 7 4]
   [6 9 2 6]
   [7 4 3 7]]

  [[7 2 5 4]
   [1 7 5 1]
   [4 0 9 5]]

  [[8 0 9 2]
   [6 3 8 2]
   [4 2 6 4]]

  [[8 6 1 3]
   [8 1 9 8]
   [9 4 1 3]]]


 [[[6 7 2 0]
   [3 1 7 3]
   [1 5 5 9]]

  [[3 5 1 9]
   [1 9 3 7]
   [6 8 7 4]]

  [[1 4 7 9]
   [8 8 0 8]
   [6 8 7 0]]

  [[7 7 2 0]
   [7 2 2 0]
   [4 9 6 9]]]


 [[[8 6 8 7]
   [1 0 6 6]
   [7 4 2 7]]

  [[5 2 0 2]
   [4 2 0 4]
   [9 6 6 8]]

  [[9 9 2 6]
   [0 3 3 4]
   [6 6 3 6]]

  [[2 5 1 9]
   [8 4 5 3]
   [9 6 8 6]]]]

Sum Over the Last Two Axes:
[[64 50 54 61]
 [49 63 66 55]
 [62 48 57 66]]
